[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"

[functions]
  external_node_modules = ["express", "multer"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "22"

[functions."*"]
  runtime = "nodejs22.x"
  included_files = ["node_modules/**"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"